services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception_network
    restart: always
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    secrets:
      - db_password
      - credentials
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception_network
    restart: always
    depends_on:
      - mariadb
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - WordPress:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception_network
    restart: always
    depends_on:
      - wordpress

volumes:
  DB:
    name: DB
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/DB
  WordPress:
    name: WordPress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/WordPress

networks:
  inception_network:
    driver: bridge
    name: inception_network

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt